name: mlops-churn

channels:
  - conda-forge
  - defaults

dependencies:
  - python =3.11
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - matplotlib
  - pyyaml
  - jupyter
  - pip
  - pip:
      - wandb
      - fastapi
      - uvicorn[standard]
      - pydantic
      - python-dotenv
      - httpx
      - pytest
